# Generated by Django 3.2.13 on 2022-12-02 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=25)),
                ('prenom_personnel', models.CharField(max_length=200)),
                ('nom_personnel', models.CharField(max_length=200)),
                ('telephone_personnel', models.CharField(max_length=25, null=True)),
                ('adresse_personnel', models.CharField(max_length=500, null=True)),
                ('profile', models.CharField(choices=[('médecin', 'Médecin'), ('paramédical', 'Paramédical'), ('ambulancier', 'Ambulancier')], max_length=25)),
                ('specialite', models.CharField(max_length=250, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'personnel',
            },
        ),
    ]
