# Generated by Django 3.2.13 on 2022-12-02 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=200)),
                ('nom', models.CharField(max_length=100)),
                ('age', models.IntegerField(null=True)),
                ('sexe', models.CharField(max_length=5)),
                ('adresse', models.CharField(max_length=500)),
                ('telephone', models.CharField(max_length=50)),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'patient',
            },
        ),
    ]
