# Generated by Django 3.2.13 on 2022-12-06 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consommable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_consommable', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'consommables',
            },
        ),
        migrations.CreateModel(
            name='Lesions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_lesion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'lesion',
            },
        ),
        migrations.CreateModel(
            name='Organe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_organe', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'organe',
            },
        ),
        migrations.CreateModel(
            name='Rubrique_signe_de_vie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_rubrique', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'rubrique_signe_de_vie',
            },
        ),
        migrations.CreateModel(
            name='Signe_de_vie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_signe', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'signe_de_vie',
            },
        ),
        migrations.CreateModel(
            name='traitement_primaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mise_en_condition', models.CharField(max_length=50)),
                ('solute_drogue', models.CharField(max_length=200)),
                ('voie_aerienne', models.CharField(max_length=100)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
            options={
                'db_table': 'traitement_primaire',
            },
        ),
        migrations.CreateModel(
            name='Score_signe_de_vie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(null=True)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
                ('rubrique_signe_vie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.rubrique_signe_de_vie')),
                ('signe_vie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.signe_de_vie')),
            ],
            options={
                'db_table': 'score_signe_de_vie',
            },
        ),
        migrations.CreateModel(
            name='Origine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pays_origine', models.CharField(max_length=20)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
            options={
                'db_table': 'origine',
            },
        ),
        migrations.CreateModel(
            name='Horaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('heure', models.CharField(max_length=25)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
            options={
                'db_table': 'horaire',
            },
        ),
        migrations.CreateModel(
            name='Diagnostique_lesion_organe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultat_diagnostique', models.CharField(max_length=100)),
                ('lesion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.lesions')),
                ('organe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.organe')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
            options={
                'db_table': 'diagnostique_lesion_organe',
            },
        ),
        migrations.CreateModel(
            name='Detail_patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origine_appel', models.CharField(max_length=100)),
                ('Motif_appel', models.CharField(max_length=150)),
                ('nom_appelant', models.CharField(max_length=150)),
                ('telephone_appelant', models.CharField(max_length=50)),
                ('lieu_intervention', models.CharField(max_length=100)),
                ('decision', models.CharField(max_length=100)),
                ('trajet', models.CharField(max_length=200)),
                ('numero_ambulance', models.CharField(max_length=20)),
                ('diagnostique_evoque', models.CharField(max_length=250)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
            options={
                'db_table': 'detail_patient',
            },
        ),
        migrations.CreateModel(
            name='consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_consulte', models.CharField(max_length=100)),
                ('heure', models.CharField(max_length=20)),
                ('resultat', models.CharField(max_length=50)),
                ('commentaire', models.CharField(max_length=150)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
            options={
                'db_table': 'consultation',
            },
        ),
        migrations.CreateModel(
            name='Consommable_utilise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_consommable_utilise', models.CharField(max_length=100)),
                ('nombre', models.IntegerField(null=True)),
                ('charges', models.CharField(max_length=100)),
                ('fnc', models.CharField(max_length=100)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
            options={
                'db_table': 'consommables_utilises',
            },
        ),
        migrations.CreateModel(
            name='Autre_indice_signe_vie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fourmillement_extremites', models.CharField(max_length=10)),
                ('mouvement_des_ms', models.CharField(max_length=10)),
                ('mouvement_des_mi', models.CharField(max_length=10)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
            options={
                'db_table': 'autres_indice_signe_vie',
            },
        ),
    ]
