# Generated by Django 3.2.13 on 2022-12-06 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_autre_indice_signe_vie_consommable_consommable_utilise_consultation_detail_patient_diagnostique_lesi'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail_patient',
            name='ambulancier',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='detail_patient',
            name='medecin',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='detail_patient',
            name='paramedical',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
