# Generated by Django 3.2.13 on 2022-12-07 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_auto_20221206_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnostique_lesion_organe',
            name='organe_id',
        ),
        migrations.AddField(
            model_name='diagnostique_lesion_organe',
            name='organe',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
