# Generated by Django 3.2.13 on 2022-12-08 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_rename_organe_diagnostique_lesion_organe_nom_organe'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubrique_signe_de_vie',
            name='commentaire_score',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rubrique_signe_de_vie',
            name='score',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='rubrique_signe_de_vie',
            name='signe_de_vie_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.signe_de_vie'),
        ),
    ]
